//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Xml.Serialization;

namespace Biztalk2013R2PartnerAgreementManager.XmlSettings
{
    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.33440.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Identifiers
    {

        private string iSA05Field;

        private string iSA06Field;

        private string iSA07Field;

        private string iSA08Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ISA05
        {
            get
            {
                return this.iSA05Field;
            }
            set
            {
                this.iSA05Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ISA06
        {
            get
            {
                return this.iSA06Field;
            }
            set
            {
                this.iSA06Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ISA07
        {
            get
            {
                return this.iSA07Field;
            }
            set
            {
                this.iSA07Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ISA08
        {
            get
            {
                return this.iSA08Field;
            }
            set
            {
                this.iSA08Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class X12OnewayAgreementInterchangeSettings
    {
       
        private InterchangeSettingsAcknowledgement acknowledgementField;

        private InterchangeSettingsCharacterSetAndSeparators characterSetAndSeparatorsField;
       
        //private List<SendportReference> sendPortsField;
       
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Acknowledgement", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterchangeSettingsAcknowledgement Acknowledgement
        {
            get
            {
                return this.acknowledgementField;
            }
            set
            {
                this.acknowledgementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CharacterSetAndSeparators", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterchangeSettingsCharacterSetAndSeparators CharacterSetAndSeparators
        {
            get
            {
                return this.characterSetAndSeparatorsField;
            }
            set
            {
                this.characterSetAndSeparatorsField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //[System.Xml.Serialization.XmlArrayItemAttribute("Sendport", typeof(SendportReference), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        //public List<SendportReference> SendPorts
        //{
          //  get
           /* {
                return this.sendPortsField;
            }
            set
            {
                this.sendPortsField = value;
            }
        }
        */

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class AS2OnewayAgreementMDNAcknowledgementSettings
    {



        private string signingAlgorithm;
        private string receiptDeliveryOptionUrl;





        [System.Xml.Serialization.XmlElementAttribute("SigningAlgorithm", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SigningAlgorithm
        {
            get
            {
                return this.signingAlgorithm;
            }
            set
            {
                this.signingAlgorithm = value;
            }
        }
        [System.Xml.Serialization.XmlElementAttribute("ReceiptDeliveryOptionUrl", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceiptDeliveryOptionUrl
        {
            get
            {
                return this.receiptDeliveryOptionUrl;
            }
            set
            {
                this.receiptDeliveryOptionUrl = value;
            }
        }


    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class X12OnewayAgreementTransactionSetSettings
    {



        private List<X12AgreementTransactionSetSettingsEnvelope> transactionSetSettingsEnvelopeField;
        private List<X12AgreementTransactionSetSettingsSchemaOveride> transactionSetSettingsSchemaOveridesList;




        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Envelope", typeof(X12AgreementTransactionSetSettingsEnvelope), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<X12AgreementTransactionSetSettingsEnvelope> Envelopes
        {
            get
            {
                return this.transactionSetSettingsEnvelopeField;
            }
            set
            {
                this.transactionSetSettingsEnvelopeField = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SchemaOveride", typeof(X12AgreementTransactionSetSettingsSchemaOveride), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<X12AgreementTransactionSetSettingsSchemaOveride> SchemaOverides
        {
            get
            {
                return this.transactionSetSettingsSchemaOveridesList;
            }
            set
            {
                this.transactionSetSettingsSchemaOveridesList = value;
            }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class InterchangeSettingsAcknowledgement
    {

        private string expect997Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Expect997
        {
            get
            {
                return this.expect997Field;
            }
            set
            {
                this.expect997Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class InterchangeSettingsCharacterSetAndSeparators
    {

        private string dataElementSeparatorField;

        private string componentElementSeparatorField;

        private string segmentTerminatorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DataElementSeparator
        {
            get
            {
                return this.dataElementSeparatorField;
            }
            set
            {
                this.dataElementSeparatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ComponentElementSeparator
        {
            get
            {
                return this.componentElementSeparatorField;
            }
            set
            {
                this.componentElementSeparatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SegmentTerminator
        {
            get
            {
                return this.segmentTerminatorField;
            }
            set
            {
                this.segmentTerminatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SendportReference
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class Batch
    {

        private string nameField;
        private List<FilterGroup> lstFilterGrps;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("FilterGroup", typeof(FilterGroup), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<FilterGroup> FilterGroups
        {
            get
            {
                return this.lstFilterGrps;
            }
            set
            {
                this.lstFilterGrps = value;
            }
        }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class FilterGroup
    {

       
        private List<Filter> lstFilters;

      
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Filter", typeof(Filter), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<Filter> Filters
        {
            get
            {
                return this.lstFilters;
            }
            set
            {
                this.lstFilters = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class Filter
    {

        private string filterProperty,filterOperator,filterValue;
       
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FilterProperty
        {
            get
            {
                return this.filterProperty;
            }
            set
            {
                this.filterProperty = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FilterOperator
        {
            get
            {
                return this.filterOperator;
            }
            set
            {
                this.filterOperator = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FilterValue
        {
            get
            {
                return this.filterValue;
            }
            set
            {
                this.filterValue= value;
            }
        }
        
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AgreementAlias
    {

        private string aliasKeyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AliasKey
        {
            get
            {
                return this.aliasKeyField;
            }
            set
            {
                this.aliasKeyField = value;
            }
        }
        private string aliasvalueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AliasValue
        {
            get
            {
                return this.aliasvalueField;
            }
            set
            {
                this.aliasvalueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class X12AgreementTransactionSetSettingsEnvelope
    {

        private string transactionTypeField;

        private string versionField;

        private string targetNamespaceField;

        private string gS1Field;

        private string gS2Field;

        private string gS3Field;

        private string gS4Field;

        private string gS5Field;

        private string gS7Field;

        private string gS8Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TransactionType
        {
            get
            {
                return this.transactionTypeField;
            }
            set
            {
                this.transactionTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TargetNamespace
        {
            get
            {
                return this.targetNamespaceField;
            }
            set
            {
                this.targetNamespaceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GS1
        {
            get
            {
                return this.gS1Field;
            }
            set
            {
                this.gS1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GS2
        {
            get
            {
                return this.gS2Field;
            }
            set
            {
                this.gS2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GS3
        {
            get
            {
                return this.gS3Field;
            }
            set
            {
                this.gS3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GS4
        {
            get
            {
                return this.gS4Field;
            }
            set
            {
                this.gS4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GS5
        {
            get
            {
                return this.gS5Field;
            }
            set
            {
                this.gS5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GS7
        {
            get
            {
                return this.gS7Field;
            }
            set
            {
                this.gS7Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GS8
        {
            get
            {
                return this.gS8Field;
            }
            set
            {
                this.gS8Field = value;
            }
        }
    }
     /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class X12AgreementTransactionSetSettingsSchemaOveride
    {

        private string transactionTypeField;

        private string versionField;

        private string targetNamespaceField;

       
        private string gS2Field;


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TransactionType
        {
            get
            {
                return this.transactionTypeField;
            }
            set
            {
                this.transactionTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TargetNamespace
        {
            get
            {
                return this.targetNamespaceField;
            }
            set
            {
                this.targetNamespaceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GS2
        {
            get
            {
                return this.gS2Field;
            }
            set
            {
                this.gS2Field = value;
            }
        }

     

     
    }
    


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class BiztalkPartySettings
    {

        private List<Party> itemsField;

      
        [System.Xml.Serialization.XmlElementAttribute("Party", typeof(Party), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<Party> Parties
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class Party
    {

        private string nameField;

        private List<BusinessProfile> businessProfilesField;
        private List<SendportReference> sendPortsField;
        /// <remarks/>
        /// 

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Sendport", typeof(SendportReference), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<SendportReference> SendPorts
        {
            get
            {
                return this.sendPortsField;
            }
            set
            {
                this.sendPortsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("BusinessProfile", typeof(BusinessProfile), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<BusinessProfile> BusinessProfiles
        {
            get
            {
                return this.businessProfilesField;
            }
            set
            {
                this.businessProfilesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BusinessProfile
    {

        private string nameField;

        private List<BusinessProfileIdentity> identitiesField;

        private List<BusinessProfileAgreement> agreementsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Identity", typeof(BusinessProfileIdentity), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<BusinessProfileIdentity> Identities
        {
            get
            {
                return this.identitiesField;
            }
            set
            {
                this.identitiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Agreement", typeof(BusinessProfileAgreement), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<BusinessProfileAgreement> Agreements
        {
            get
            {
                return this.agreementsField;
            }
            set
            {
                this.agreementsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BusinessProfileIdentity
    {

        private string identityQualifier;
        private string identityDesc;
        private string identityValue;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IdentityQualifier", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdentityQualifier
        {
            get
            {
                return this.identityQualifier;
            }
            set
            {
                this.identityQualifier = value;
            }
        }
        [System.Xml.Serialization.XmlElementAttribute("IdentityDesc",Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdentityDesc
        {
            get
            {
                return this.identityDesc;
            }
            set
            {
                this.identityDesc = value;
            }
        }
        [System.Xml.Serialization.XmlElementAttribute("IdentityValue",Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdentityValue
        {
            get
            {
                return this.identityValue;
            }
            set
            {
                this.identityValue = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BusinessProfileAgreement
    {

        private string nameField;

        private string protocolField;

        private BusinessProfileAgreementFirstParty firstPartyField;

        private BusinessProfileAgreementSecondParty secondPartyField;

        private BusinessProfileFirstPartyToSecondPartyOneWayAgreement firstPartyToSecondPartyOneWayAgreementField;

        private BusinessProfileSecondPartyToFirstPartyOneWayAgreement secondPartyToFirstPartyOneWayAgreementField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Protocol
        {
            get
            {
                return this.protocolField;
            }
            set
            {
                this.protocolField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FirstParty", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusinessProfileAgreementFirstParty FirstParty
        {
            get
            {
                return this.firstPartyField;
            }
            set
            {
                this.firstPartyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SecondParty", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusinessProfileAgreementSecondParty SecondParty
        {
            get
            {
                return this.secondPartyField;
            }
            set
            {
                this.secondPartyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FirstPartyToSecondPartyOneWayAgreement", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusinessProfileFirstPartyToSecondPartyOneWayAgreement FirstPartyToSecondPartyOneWayAgreement
        {
            get
            {
                return this.firstPartyToSecondPartyOneWayAgreementField;
            }
            set
            {
                this.firstPartyToSecondPartyOneWayAgreementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SecondPartyToFirstPartyOneWayAgreement", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusinessProfileSecondPartyToFirstPartyOneWayAgreement SecondPartyToFirstPartyOneWayAgreement
        {
            get
            {
                return this.secondPartyToFirstPartyOneWayAgreementField;
            }
            set
            {
                this.secondPartyToFirstPartyOneWayAgreementField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BusinessProfileAgreementFirstParty
    {

        private string nameField;

        private string businessProfileNameField;

        private BusinessProfileIdentity idenityField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BusinessProfileName
        {
            get
            {
                return this.businessProfileNameField;
            }
            set
            {
                this.businessProfileNameField = value;
            }
        }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusinessProfileIdentity Identity
        {
            get
            {
                return this.idenityField;
            }
            set
            {
                this.idenityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BusinessProfileAgreementSecondParty
    {

        private string nameField;

        private string businessProfileNameField;
        private BusinessProfileIdentity idenityField;
        /// <remarks/>

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Name",Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BusinessProfileName",Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BusinessProfileName
        {
            get
            {
                return this.businessProfileNameField;
            }
            set
            {
                this.businessProfileNameField = value;
            }
        }
        [System.Xml.Serialization.XmlElementAttribute("Identity",Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusinessProfileIdentity Identity
        {
            get
            {
                return this.idenityField;
            }
            set
            {
                this.idenityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BusinessProfileFirstPartyToSecondPartyOneWayAgreement
    {

       

        private X12OnewayAgreementInterchangeSettings interchangeSettingsField;
        private X12OnewayAgreementTransactionSetSettings transactionSettingsField;
        private AS2OnewayAgreementMDNAcknowledgementSettings mdnAcknowledgementSettingsField;
        private List<AgreementAlias> agreementAliases;
        private List<SendportReference> sendPortsField;
        private List<Batch> batchesLst;
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Batch", typeof(Batch), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<Batch> Batches
        {
            get
            {
                return this.batchesLst;
            }
            set
            {
                this.batchesLst = value;
            }
        }
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AgreementAlias", typeof(AgreementAlias), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<AgreementAlias> AgreementAliases
        {
            get
            {
                return this.agreementAliases;
            }
            set
            {
                this.agreementAliases = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Sendport", typeof(SendportReference), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<SendportReference> SendPorts
        {
            get
            {
                return this.sendPortsField;
            }
            set
            {
                this.sendPortsField = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InterchangeSettings")]
        public X12OnewayAgreementInterchangeSettings InterchangeSettings
        {
            get
            {
                return this.interchangeSettingsField;
            }
            set
            {
                this.interchangeSettingsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TransactionSetSettings")]
        public X12OnewayAgreementTransactionSetSettings TransactionSettings
        {
            get
            {
                return this.transactionSettingsField;
            }
            set
            {
                this.transactionSettingsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MDNAcknowledgementSettings")]
        public AS2OnewayAgreementMDNAcknowledgementSettings MDNAcknowledgementSettings
        {
            get
            {
                return this.mdnAcknowledgementSettingsField;
            }
            set
            {
                this.mdnAcknowledgementSettingsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BusinessProfileSecondPartyToFirstPartyOneWayAgreement
    {

       

        private X12OnewayAgreementInterchangeSettings interchangeSettingsField;
        private X12OnewayAgreementTransactionSetSettings transactionSettingsField;

        private AS2OnewayAgreementMDNAcknowledgementSettings mdnAcknowledgementSettingsField;
        private List<AgreementAlias> agreementAliases;
        private List<SendportReference> sendPortsField;
        
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AgreementAlias", typeof(AgreementAlias), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<AgreementAlias> AgreementAliases
        {
            get
            {
                return this.agreementAliases;
            }
            set
            {
                this.agreementAliases = value;
            }
        }
        private List<Batch> batchesField;
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Batch", typeof(Batch), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<Batch> Batches
        {
            get
            {
                return this.batchesField;
            }
            set
            {
                this.batchesField = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Sendport", typeof(SendportReference), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<SendportReference> SendPorts
        {
            get
            {
                return this.sendPortsField;
            }
            set
            {
                this.sendPortsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InterchangeSettings")]
        public X12OnewayAgreementInterchangeSettings InterchangeSettings
        {
            get
            {
                return this.interchangeSettingsField;
            }
            set
            {
                this.interchangeSettingsField = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TransactionSetSettings")]
        public X12OnewayAgreementTransactionSetSettings TransactionSettings
        {
            get
            {
                return this.transactionSettingsField;
            }
            set
            {
                this.transactionSettingsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MDNAcknowledgementSettings")]
        public AS2OnewayAgreementMDNAcknowledgementSettings MDNAcknowledgementSettings
        {
            get
            {
                return this.mdnAcknowledgementSettingsField;
            }
            set
            {
                this.mdnAcknowledgementSettingsField = value;
            }
        }
    }
}